name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Git pull
      run: |
        cd
        git pull https://github.com/DBH-Docs/Documentation.git
        npm i