name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Git clone
      run: |
        cd
        git clone https://github.com/DBH-Docs/Documentation.git
        mv -f ~/Documentation/* ~/
        npm i
        rm -r Documentation 
